### ISSUE TITLE
Text Editor Never Leaves Edit Mode/Prevents Saving

### ISSUE THREAD

**Issue by NerdEyeIndustries** [fvtt-fria-ligan/forbidden-lands-foundry-vtt#363]
### Describe the bug

None of the games text editors are functioning..  Editor never leaves edit mode when you click save.

### Reproduction

(See character/bio tab)

### System Info

```shell
Foundry 11
```

### Logs

No log entries (errors or warnings)

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Forbidden Lands system).
- [X] Not a bug report about the content modules. Reports regarding the content modules go [here instead](https://github.com/aMediocreDad/fbl-content-modules/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
- [X] Not a "How To"-question (You can ask questions here: [Discussions](https://github.com/fvtt-fria-ligan/forbidden-lands-foundry-vtt/discussions)).

**Comment by Zanion** [comment]
+1
Reproduced in my instance as well Foundry V10. This defect is observed as preventing any item/actor descriptions from being saved.

Console error on item effect save:
```
Uncaught (in promise) Error: system.effect is not an active editor name!
    at ForbiddenLandsGearSheet.saveEditor (foundry.js:6060:46)
    at jR.save_onsavecallback (foundry.js:6102:39)
    at plugin.min.js:4:1197
    at jR.<anonymous> (plugin.min.js:4:1412)
    at commands.exec.<computed> (tinymce.min.js:4:358670)
    at iR.execCommand (tinymce.min.js:4:358116)
    at jR.execCommand (tinymce.min.js:4:383782)
    at Object.onAction (plugin.min.js:4:842)
    at theme.min.js:4:261255
    at theme.min.js:4:118394
    at theme.min.js:4:261224
    at theme.min.js:4:29516
    at N (theme.min.js:4:2455)
    at run (theme.min.js:4:29501)
    at theme.min.js:4:30368
    at theme.min.js:4:782
    at theme.min.js:4:139333
    at B.fold (theme.min.js:4:1075)
    at fx (theme.min.js:4:139241)
    at bx (theme.min.js:4:139633)
    at vx (theme.min.js:4:139720)
    at theme.min.js:4:141481
    at theme.min.js:4:37522
    at li (theme.min.js:4:38286)
    at Object.triggerEvent (theme.min.js:4:141470)
    at Cr (theme.min.js:4:25368)
    at xr (theme.min.js:4:25213)
    at Sr (theme.min.js:4:25276)
    at e (theme.min.js:4:86243)
    at theme.min.js:4:30368
    at theme.min.js:4:782
    at theme.min.js:4:139333
    at B.fold (theme.min.js:4:1075)
    at fx (theme.min.js:4:139241)
    at bx (theme.min.js:4:139633)
    at vx (theme.min.js:4:139720)
    at theme.min.js:4:141389
    at theme.min.js:4:141410
    at theme.min.js:4:37522
    at li (theme.min.js:4:38286)
    at Object.triggerEvent (theme.min.js:4:141359)
    at theme.min.js:4:138209
    at HTMLDivElement.<anonymous> (theme.min.js:4:13954)
    ```
